# Configurações de Trading
trading:
  symbol: BTCUSDT
  timeframe: 1m           # Alterado para 1m para maior granularidade
  max_positions: 3
  position_size: 0.01
  use_leverage: false
  max_leverage: 1
  min_order_interval: 60  # Reduzido para 60 segundos
  signal_threshold: 0.15  # Novo parâmetro para filtrar sinais

# Configurações de Risco
risk:
  max_daily_trades: 10
  max_daily_drawdown: 0.02  # 2%
  max_total_exposure: 0.5   # 50% do capital
  risk_per_trade: 0.01     # 1% por trade
  capital: 1000.0          # Capital inicial
  reserve_ratio: 0.1       # 10% de reserva
  max_position_size: 100.0
  max_position_ratio: 0.1  # 10% do capital por posição

# Configurações de Análise
analysis:
  indicators:
    rsi:
      period: 14
      oversold: 35        # Ajustado
      overbought: 65      # Ajustado
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9
      min_strength: 100   # Novo: força mínima do MACD
    bollinger_bands:
      period: 20
      std_dev: 2
      min_width: 0.015   # Novo: largura mínima
    moving_averages:
      short_period: 9
      long_period: 21
    adx:                 # Novo indicador
      period: 14
      min_strength: 10
    stochastic:         # Novo indicador
      k_period: 14
      d_period: 3
      oversold: 20
      overbought: 80

  divergence:           # Nova seção
    enabled: true
    min_severity: "low"
    confirmation_period: 3

  ml:
    confidence_threshold: 0.7  # Reduzido para alinhar com min_confidence
    training_period: 30        # Reduzido para 30 dias
    retraining_interval: 12    # Reduzido para 12 horas
    features:
      - rsi
      - macd
      - bollinger_bands
      - volume
      - price_change
      - adx              # Novo feature
      - stochastic      # Novo feature

# Configurações de Monitoramento
monitoring:
  alert_interval: 300     # Reduzido para 5 minutos
  report_interval: 3600   # Reduzido para 1 hora
  metrics_history_size: 1000
  thresholds:
    profit_warning: -0.015
    profit_critical: -0.03
    latency_warning: 1.0   # Reduzido para maior sensibilidade
    memory_warning: 0.85
    api_errors_threshold: 2 # Mais restritivo

# Resto do arquivo mantido igual...